name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 */15 * *" # 每 15 天一次
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      # Step 1: Checkout target repo
      - name: Checkout target repo
        uses: actions/checkout@v3

      # Step 2: Add upstream repository and fetch changes
      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/cmliu/WorkerVless2sub.git
          git fetch upstream main

      # Step 3: Merge changes, excluding workflows
      - name: Merge upstream changes
        run: |
          git merge --no-commit --no-ff upstream/main
          git restore --staged .github/workflows
          git commit -m "Sync from upstream, excluding workflows"
      
      # Step 4: Push changes to the fork repository
      - name: Push changes
        run: |
          git push origin main
